# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75936afa0a5918624311fd478b7628a6fc67ba027543beaa75e393a74c7f1b28638c98b0b277b8a37c0746eccc23dc7eaf8b00cf4cb107765253ecd47c09f925

test:
  secret_key_base: 6552c0c371a9ba1ac1bd14a5ab04db954abc3e698ca700538367d7a703afb0152d89fb90ad257ac0d5b8876627d539167e562d6b15691696042de7516531f54e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
